services:
  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

  metrics_service:
    build: ./metrics_service
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: 12345pass
      POSTGRES_DB: health_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
